### ISSUE TITLE
Missing link to sustainability report

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#135]
![Image](https://github.com/Klimatbyran/beta/assets/165904444/5958aca1-a6f4-484c-a0f1-0f70b4a329f0)

Some companies are missing the link to the sustainability report:
Volvo AB
Vitrolife
Troax
Tietoevry
Telia
Tele2

**Comment by Greenheart** [comment]
Confirmed. For some reason, the url is missing. https://beta.klimatkollen.se/foretag/volvo-group-Q163810

We could fall back to the `facit.url` if it's present and that would hopefully solve this issue for some companies. I'll take a look.
