### ISSUE TITLE
Approved reports not on site

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#136]
I re-ran Wihlborgs and Nordea and approved them, yet there is no new data on the site.

**Comment by Greenheart** [comment]
I think this got published with the latest update :)

https://beta.klimatkollen.se/foretag/wihlborgs-fastigheter-Q10720019
https://beta.klimatkollen.se/foretag/nordea-bank-Q1123823

Feel free to re-open if this is still an issue!
