### ISSUE TITLE
Stop showing decimals

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#139]
![Image](https://github.com/Klimatbyran/beta/assets/165904444/5848dffb-e260-47c2-87ed-93c87366d3f0)

It's confusing to show decimals, since , is used as a separator for 000 in English. We can round off to closest tonne

**Comment by Greenheart** [comment]
Thanks @Almendra-ab! Feel free to open more issues with ideas and feedback :)
