### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#146]
![Image](https://github.com/Klimatbyran/beta/assets/165904444/195323e7-58cc-4c40-a3c8-0be4cccd674a)

Wihlborgs är lite svår att klicka på i listan, det verkar som att länken inte är hela ordet? Och nu när jag klickade igenom kom jag till detta:

**Comment by Almendra-ab** [comment]
Gäller även Systemair

**Comment by Almendra-ab** [comment]
Även SAS

**Comment by Greenheart** [comment]
Might be possible to reproduce by testing locally with the API data
