### ISSUE TITLE
Missing total emissions

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#149]
![Image](https://github.com/Klimatbyran/beta/assets/165904444/cd9cd6af-12b9-4bdf-82bf-5bea88fb5bdc)

Haven't seen this before, maybe works with a retry but weird

**Comment by Greenheart** [comment]
This might be caused by not reading emissions from multiple sources. We need to read from 1) facit 2) wikidata and 3) garbo emissions data.
