### ISSUE TITLE
Not showing data for latest year, when it is not 2023

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#151]
![Image](https://github.com/Klimatbyran/beta/assets/165904444/9158e2c1-8198-4f7c-98c4-d0e1b072f553)

![Image](https://github.com/Klimatbyran/beta/assets/165904444/7f8d8925-5c3e-4d3d-9bb9-e2eefe5082d1)

Garbo does not find data for 2023, in that case we need her to show data for 2022 and indicate that.
For Sectra it's unclear why, but for Lundin and a few others, 2022 is the latest year we have

**Comment by Greenheart** [comment]
More context from investigation:

- The latest report is from 2022 for some companies: This applies for Lundin, International Petroleum and Coop

**Comment by Almendra-ab** [comment]
Lagercrantz group and Sectra applies broken fiscal year, but has latest emissions data from 2022

**Comment by Greenheart** [comment]
Related to this issue: We only return 2023 `facit` emissions data. This means we aren't able to show the `verified` badge for 2022 emissions data.

This likely needs to be fixed in the API.

One example: https://beta.klimatkollen.se/foretag/lundin-mining-corp.-Q1537901
