### ISSUE TITLE
[BUG] https://beta.klimatkollen.se/foretag/ox2- shows "JM" company

### ISSUE THREAD

**Issue by LudwikJaniuk** [Klimatbyran/beta#153]
Just visit https://beta.klimatkollen.se/foretag/ox2- and you'll see.

**Comment by Greenheart** [comment]
Thanks! This seems to be because garbo gets the wrong `wikidataId`, which happens for several other companies. This needs to be fixed on the API side, in the https://github.com/Klimatbyran/garbo/ repo.
