### ISSUE TITLE
(suspected) [BUG] Q-identifiers can change

### ISSUE THREAD

**Issue by LudwikJaniuk** [Klimatbyran/beta#155]
IIUC WikiID / Q-identifiers are hardcoded on klimatkollen.se and are used as URL components to webpages (links which people could bookmark). At the same time, Garbo is IIUC permitted guess/lookup/generate the Q-id on each run. This seems like a recipe for errors - as soon as Garbo gets it wrong, the whole linking for the company collapses. 

Unless I've understood the setup wrong, I think either Q-ids should not be used by us as URL components, or they should be kept stable by code.

**Comment by Greenheart** [comment]
Resolved in the API. See comment in #154 for more details
