### ISSUE TITLE
[BUG] The sorting is broken

### ISSUE THREAD

**Issue by LudwikJaniuk** [Klimatbyran/beta#156]
![image](https://github.com/Klimatbyran/beta/assets/6298393/9ad4435c-b267-40ef-9501-ffe90f27e621)

**Comment by Greenheart** [comment]
Thanks!

Right now we only use the default sorting provided by the underlying component library. I'm not sure what order it sorts in, or which properties it looks for. 

Here's the component we built our combobox from https://www.shadcn-svelte.com/docs/components/combobox

**Comment by Greenheart** [comment]
Must have been quite tired when this was reported. Super simple fix incoming as part of https://github.com/Klimatbyran/beta/pull/199
