### ISSUE TITLE
Too many initiatives shown

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#159]
![Image](https://github.com/Klimatbyran/beta/assets/165904444/6eb6b21c-490f-44d7-b914-cd1697e3880a)

This list should not be so long, I think we agreed on 3 or 5 initiatives?

**Comment by Greenheart** [comment]
Closing in favor of related issue opened two weeks ago: https://github.com/Klimatbyran/beta/issues/70
