### ISSUE TITLE
Garbo presenting initiatives in English

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#163]
![Image](https://github.com/Klimatbyran/beta/assets/165904444/eb02a26b-054a-43c7-b830-98d02c606a49)

This is from Autoliv, text should be in Swedish

**Comment by Greenheart** [comment]
For Autoliv, the latest data was approved June 17th, which was two days before the prompt was updated to return Swedish responses (https://github.com/Klimatbyran/garbo/blob/42590adbfb32260e1381c5f3aa57561457dfc8ce/src/prompts/followUp/initiatives.ts). Re-running the report (and manually re-fixing all errors) this.

![image](https://github.com/Klimatbyran/beta/assets/6125097/8c613348-0136-4b1b-88eb-a30863510f74)

**Comment by irony** [comment]
Please verify @Almendra-ab

**Comment by Greenheart** [comment]
Alex and I spoke about this yesterday when I wrote the comment, so we're in sync on this :)

If the following report is reviewed and approved, it will solve this issue. However, any other companies which present goals/initiatives in English will still need to be re-run through Garbo.

Relevant thread: https://discord.com/channels/1049333222309371965/1201463851447758879/threads/1255087742883205161

And query to find the related report in OpenSearch: `GET /reports/_doc/b507d2af-7b04-4e4f-a0d0-28d3db17d8fa`

**Comment by Almendra-ab** [comment]
![Screenshot 2024-07-02 at 10 50 47](https://github.com/Klimatbyran/beta/assets/165904444/e4374892-903b-4c75-8207-fb1288023b18)

well...

**Comment by Greenheart** [comment]
@Almendra-ab This issue about showing initiatives in Swedish issue is now resolved.

Good catch with the formatting error when the year is missing! :) I opened a separate issue #185 to follow that up. Should be a quick fix.
