### ISSUE TITLE
Not displaying categories

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#187]
https://beta.klimatkollen.se/foretag/embracer-group-Q65083539

**Comment by Greenheart** [comment]
From investigation:

> Scope 3-kategorierna för Embracer group har bara `null`-värden. Både för wikidata och facit. Även garbos genererade data lämnar kategorierna tomma.

The condition rendering the scope 3 emissions categories needs to be updated to still show the empty categories when 0 have been reported. This is likely a `{0 && <div />}` condition in the Astro code, and should be changed to always render the scope 3 categories.
