### ISSUE TITLE
Shows no reported emissions as "0"

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#191]
https://beta.klimatkollen.se/foretag/nyfosa-Q115167358

There is a difference between no reported emissions, -, and actually reporting 0 emissions. Here it says 0 but it's actually technically unknown.

**Comment by Almendra-ab** [comment]
Reran the report and now it's fine lol

**Comment by Greenheart** [comment]
Yeah, my lesson so far is: Do not trust GPT-* or other LLMs to be accurate. Maybe in the future, but not for the forseeable future. They seem to just cause more problems than they solve.

Closing as resolved, but feel free to re-open if this appears in other cases. There might be a bug in the frontend.
