### ISSUE TITLE
AAK missing scope 3 emissions

### ISSUE THREAD

**Issue by Almendra-ab** [Klimatbyran/beta#213]
![Screenshot 2024-10-02 at 11 33 03](https://github.com/user-attachments/assets/e4a2ae59-dcfc-4a1e-8086-5ec61d615b7c)

AAK has reported emissions in scope 3 (6,817,620 tonnes), but they are not reported per category. Total scope 3 is not shown for some reason.

**Comment by Greenheart** [comment]
Confirmed fix - likely by including `statedTotalEmissions` in the API data :)
