### ISSUE TITLE
Add support for showing stated total emissions when calculated is none

### ISSUE THREAD

**Issue by hugo-nl** [Klimatbyran/beta#240]
- In the scenario that we have zero categories reported we show calculated emissions which will be 0... 
- However if they have a stated total emission then we should show that instead

**Comment by Greenheart** [comment]
`statedTotalEmissions` are now taken into account in the API endpoint where we prepare `calculatedTotalEmissions`.

This happens for `scope3.statedTotalEmissions` where we mainly had problems with this: https://github.com/Klimatbyran/garbo/blob/96a7ff2bdd483fbbaba41e30111258352a5986e1/src/routes/readCompanies.ts#L236-L25
