### ISSUE TITLE
Update fiscalYear to show the latest report period instead

### ISSUE THREAD

**Issue by Greenheart** [Klimatbyran/beta#72]
E.g. `Period: 2023` for a company that reported for 2023 and released their report in early 2024.

For fiscal years other than calendar years, we could show something like `2022/2023`, assuming 2023 is the latest year with data reported.

**Comment by Almendra-ab** [comment]
2022/2023 is how companies themselves often indicate that their fiscal year is not the same as calendar year. Which months vary. (It is possible have a fiscal year financial reporting, and a calendar year emission reporting)

**Comment by Almendra-ab** [comment]
If this is useful, it concerns the companies Addtech, Elekta, OKQ8 Scandinavia, SAS & Systemair
