### ISSUE TITLE
Lägg till Garbos publika kommentar

### ISSUE THREAD

**Issue by irony** [Klimatbyran/beta#81]
![image](https://github.com/Klimatbyran/beta/assets/395843/a8c1e00c-0300-47f0-8b26-69f48d3924f3)

**Comment by Greenheart** [comment]
Vilket fält är detta? `publicComment`, `reviewComment` eller något annat?

Hur blir det med Alex kommentarer? Det skulle öka värdet på sidan, men det är såklart mer prestige för Garbo att visa den genererade kommentaren.

Se https://github.com/Klimatbyran/beta/issues/82 för mer tankar om att visa kommentaren.
